# Generated by Django 2.2.15 on 2020-10-24 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=-1)),
                ('billing_address_id', models.IntegerField(default=-1)),
                ('area_id', models.IntegerField(default=-1)),
                ('company_id', models.IntegerField(default=-1)),
                ('company_name', models.CharField(default='', max_length=264)),
                ('company_details', models.TextField(blank=True, default='')),
                ('delivery_type_id', models.IntegerField(default=-1)),
                ('delivery_date', models.DateField(blank=True, default='')),
                ('days', models.IntegerField(default=0)),
                ('host_site', models.CharField(default='', max_length=264)),
                ('location_id', models.IntegerField(default=-1)),
                ('location_details', models.TextField(blank=True, default='')),
                ('payment_type', models.CharField(default='', max_length=264)),
                ('total_amount', models.FloatField(blank=True, default=0.0)),
            ],
        ),
    ]
