# Generated by Django 2.2.15 on 2020-09-15 06:32

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='product_images',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100000), blank=True, default=list, null=True, size=None),
        ),
    ]
