# Generated by Django 2.2.15 on 2020-09-06 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='product_reviews'),
        ),
    ]
