# Generated by Django 2.2.15 on 2020-09-01 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='groupproduct',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
