# Generated by Django 2.2.15 on 2020-09-01 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0002_auto_20200901_1427'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_name', models.CharField(blank=True, max_length=100, null=True)),
                ('sender_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('subject', models.CharField(blank=True, max_length=264, null=True)),
                ('message', models.CharField(blank=True, max_length=10000, null=True)),
                ('is_attended', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
