# Generated by Django 2.2.15 on 2020-09-06 06:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0002_auto_20200906_1128'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productimpression',
            old_name='Users',
            new_name='users',
        ),
    ]
