# Generated by Django 2.2.15 on 2020-09-06 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0003_auto_20200906_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Confirmed', 'Confirmed')], default='Processing', max_length=155, null=True),
        ),
    ]
