# Generated by Django 2.2.15 on 2020-10-25 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0003_auto_20201024_1339'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('activity_name', models.CharField(blank=True, default='', max_length=255, null=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('activity_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_supervisor_relation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supervisor_id', models.IntegerField(blank=True, default=0, null=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='productcode',
            name='SKU',
            field=models.CharField(max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='productcode',
            name='SKU_img',
            field=models.CharField(max_length=264, null=True),
        ),
    ]
