# Generated by Django 2.2.15 on 2020-09-30 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0003_auto_20200919_1639'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discount_product',
            name='start_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
