# Generated by Django 2.2.15 on 2020-09-03 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0003_contactus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='receiver_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sender_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='ticketreplies',
            name='user_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
