# Generated by Django 2.2.15 on 2020-10-01 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0004_auto_20200930_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupproduct',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='groupproduct',
            name='startdate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
