# Generated by Django 2.2.15 on 2020-09-06 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0004_order_admin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='admin_status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Processing', max_length=155, null=True),
        ),
    ]
