# Generated by Django 2.2.15 on 2020-09-06 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0005_auto_20200906_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='address',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='apartment_number',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='building_number',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='phone_number',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='road_number',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
