# Generated by Django 2.2.15 on 2020-09-08 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0006_auto_20200906_1032'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupon',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='coupon_code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='banner',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='banner',
            name='set_time',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='banner_image',
            name='Banner_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='non_verified_user_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='user_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='non_verified_user_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='product_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='comment_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='non_verified_user_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='user_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='cupons',
            name='amount',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='cupons',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='currency',
            name='role_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='discount_product',
            name='product_id',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(blank=True, choices=[('To pay', 'To pay'), ('To ship', 'To ship'), ('Received', 'Received'), ('Not Ordered', 'Not Ordered'), ('Cancelled', 'Cancelled')], default='To ship', max_length=155, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='non_verified_user_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='order_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='orderdetails',
            name='product_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='productcode',
            name='product_id',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='productimpression',
            name='product_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='productpoint',
            name='point',
            field=models.FloatField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='productpoint',
            name='product_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='currency_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='price',
            field=models.FloatField(default=-1),
        ),
        migrations.AlterField(
            model_name='productprice',
            name='product_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='productspecification',
            name='product_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='profile',
            name='user_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='non_verified_user_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='product_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.IntegerField(blank=True, choices=[(1, 'Worst'), (2, 'Bad'), (3, 'Not Bad'), (4, 'Good'), (5, 'Excellent')], default=0, null=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='user_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='role_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='tax',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='theme_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='settings',
            name='vat',
            field=models.FloatField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='receiver_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='sender_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='ticketreplies',
            name='ticket_id',
            field=models.IntegerField(default=-1),
        ),
        migrations.AlterField(
            model_name='ticketreplies',
            name='user_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='user_balance',
            name='ip_id',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='user_balance',
            name='user_id',
            field=models.IntegerField(default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='user_relation',
            name='non_verified_user_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='user_relation',
            name='verified_user_id',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='inventory',
            field=models.IntegerField(blank=True, default=-1, null=True),
        ),
        migrations.AlterField(
            model_name='variation',
            name='product_id',
            field=models.IntegerField(default=-1),
        ),
    ]
