# Generated by Django 2.2.15 on 2020-10-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0007_auto_20201001_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productspecification',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
