# Generated by Django 2.2.15 on 2020-09-09 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0007_auto_20200908_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='title',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
