# Generated by Django 2.2.15 on 2020-10-04 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0008_auto_20201003_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='origin',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='shipping_country',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='warranty',
            field=models.CharField(blank=True, default='', max_length=200, null=True),
        ),
    ]
