# Generated by Django 2.2.15 on 2020-10-04 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0009_auto_20201004_1038'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ordered_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
