# Generated by Django 2.2.15 on 2020-10-05 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0012_auto_20201004_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreplies',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
