# Generated by Django 2.2.15 on 2020-10-05 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0013_ticketreplies_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreplies',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
    ]
