# Generated by Django 2.2.15 on 2020-10-05 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0014_ticketreplies_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='commentreply',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='reviews',
            name='date_created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
