# Generated by Django 2.2.15 on 2020-10-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0015_auto_20201005_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_attended',
            field=models.BooleanField(default=False),
        ),
    ]
