# Generated by Django 2.2.15 on 2020-10-06 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0016_ticket_is_attended'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingaddress',
            name='area',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='area',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
