# Generated by Django 2.2.15 on 2020-10-06 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0017_auto_20201006_1059'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='', max_length=64),
        ),
    ]
