# Generated by Django 2.2.15 on 2020-10-06 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0019_auto_20201006_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billingaddress',
            name='area',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='billingaddress',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
