# Generated by Django 2.2.15 on 2020-10-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0020_auto_20201006_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest_user',
            name='non_verified_user_id',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
