# Generated by Django 2.2.15 on 2020-10-08 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0021_guest_user_non_verified_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
    ]
