# Generated by Django 2.2.15 on 2020-10-08 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0022_auto_20201008_0935'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pwd',
            field=models.CharField(default='', max_length=568),
        ),
    ]
