# Generated by Django 2.2.15 on 2020-10-10 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0024_auto_20201008_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='admin_approval',
            field=models.BooleanField(default=False),
        ),
    ]
