# Generated by Django 2.2.15 on 2020-10-10 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0025_product_admin_approval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='admin_approval',
        ),
        migrations.AddField(
            model_name='product',
            name='product_admin_status',
            field=models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Processing', max_length=155, null=True),
        ),
    ]
