# Generated by Django 2.2.15 on 2020-10-12 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0027_auto_20201010_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='priority',
            field=models.IntegerField(default=-1),
        ),
    ]
