# Generated by Django 2.2.15 on 2020-10-13 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0028_advertisement_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(blank=True, max_length=264, null=True)),
                ('shop_location', models.CharField(blank=True, max_length=2048, null=True)),
                ('product_quantity', models.IntegerField(null=True)),
                ('specification_id', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_name', models.CharField(blank=True, max_length=264, null=True)),
                ('warehouse_location', models.CharField(blank=True, max_length=2048, null=True)),
                ('product_quantity', models.IntegerField(null=True)),
                ('specification_id', models.IntegerField(null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='priority',
        ),
    ]
