# Generated by Django 2.2.15 on 2020-10-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0029_auto_20201013_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='priority',
            field=models.IntegerField(default=-1),
        ),
    ]
