# Generated by Django 2.2.15 on 2020-10-13 06:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0031_auto_20201013_1106'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productspecification',
            old_name='total_quantity',
            new_name='quantity',
        ),
    ]
