# Generated by Django 2.2.15 on 2020-10-13 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0032_auto_20201013_1206'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='shop_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='product_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='specification_id',
            field=models.IntegerField(default=-1, null=True),
        ),
    ]
