# Generated by Django 2.2.15 on 2020-10-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0033_auto_20201013_1227'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouse',
            name='warehouse_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
