# Generated by Django 2.2.15 on 2020-10-13 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0034_warehouse_warehouse_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='shop_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='warehouse_quantity',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
