# Generated by Django 2.2.15 on 2020-10-15 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0035_auto_20201013_1727'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventory_Price',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField(blank=True, default=-1, null=True)),
                ('specification_id', models.IntegerField(blank=True, default=-1, null=True)),
                ('quantity', models.IntegerField(blank=True, default=0)),
                ('date', models.DateField(blank=True, default='')),
                ('price', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.AddField(
            model_name='orderdetails',
            name='remaining',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
