# Generated by Django 2.2.15 on 2020-10-19 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0036_auto_20201015_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner',
            name='is_active',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
