# Generated by Django 2.2.15 on 2020-10-19 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0039_auto_20201019_1238'),
    ]

    operations = [
        migrations.AddField(
            model_name='banner_image',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
