# Generated by Django 2.2.15 on 2020-10-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0040_banner_image_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShopInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_id', models.IntegerField(blank=True, default=-1)),
                ('specification_id', models.IntegerField(blank=True, default=-1)),
                ('quantity', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.CreateModel(
            name='WarehouseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('warehouse_id', models.IntegerField(blank=True, default=-1)),
                ('specification_id', models.IntegerField(blank=True, default=-1)),
                ('quantity', models.IntegerField(blank=True, default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='shop',
            name='date',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='shop_quantity',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='specification_id',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='warehouse_quantity',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='date',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='product_quantity',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='shop_quantity',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='specification_id',
        ),
        migrations.RemoveField(
            model_name='warehouse',
            name='warehouse_quantity',
        ),
        migrations.AlterField(
            model_name='shop',
            name='shop_location',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='warehouse_location',
            field=models.CharField(blank=True, max_length=264, null=True),
        ),
    ]
