# Generated by Django 2.2.15 on 2020-10-20 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0041_auto_20201019_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='is_active',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
