# Generated by Django 2.2.15 on 2020-10-20 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0042_advertisement_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopinfo',
            name='product_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
        migrations.AddField(
            model_name='warehouseinfo',
            name='product_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
