# Generated by Django 2.2.15 on 2020-10-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Intense', '0043_auto_20201020_1623'),
    ]

    operations = [
        migrations.CreateModel(
            name='inventory_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.IntegerField()),
                ('debit', models.IntegerField(blank=True, null=True)),
                ('credit', models.IntegerField(blank=True, null=True)),
                ('warehouse_id', models.IntegerField(blank=True, null=True)),
                ('shop_id', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
            ],
        ),
    ]
